### ISSUE TITLE
Js in html issues: Script tags not working but inline script works

### ISSUE THREAD

**Issue by injune1123** [sstur/draft-js-utils#81]
Thanks for the awesome work. I used draft-js-import-html in my project and it worked pretty well.
I am trying to display the current time in the HTML and ran into problems:

Event handlers work but script tags do not. 

An example of  event handlers
![screen shot 2017-05-19 at 2 22 14 pm](https://cloud.githubusercontent.com/assets/12467641/26261283/9fb4fd3a-3c9e-11e7-8d01-a9304e1ad60d.png)

An example of  script tags

![screen shot 2017-05-19 at 2 23 03 pm](https://cloud.githubusercontent.com/assets/12467641/26261311/b5915932-3c9e-11e7-975c-931f7bef5d34.png)

Does anyone have any idea why this happens? Thanks in advance.

**Comment by sstur** [comment]
Scripts are not really supported because it's too risky (in terms of xss) for user created content. I don't think there's an equivalent in draft-js contentState for `<script>`. Also it could allow content to modify itself (such as in your example) which could break React.

You can solve some use cases by using custom elements to represent buttons and dates for instance. Draft is very customizable in that regard.

**Comment by injune1123** [comment]
Thanks for your prompt reply @sstur . After discussing with other engineers in the team, I also realized that scripts should not be supported in the widget. Then the issue becomes that event handlers are WORKING in draft-js-export-html, which can be a security hole.
